# ── Colores de pywal (regenerados en cada cambio de wallpaper) ──
include ~/.cache/wal/colors-kitty.conf

font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        13

window_padding_width      12
background_opacity        0.85
background_blur           1
hide_window_decorations   yes
confirm_os_window_close   0

cursor_shape              beam
cursor_blink_interval     0.6
scrollback_lines          10000

enable_audio_bell         no
allow_remote_control      yes
shell_integration         enabled

tab_bar_edge              top
tab_bar_style             powerline
tab_powerline_style       slanted

# Recarga de config en caliente
map ctrl+shift+r load_config_file
map ctrl+shift+enter launch --cwd=current
