general {
    lock_cmd = pidof hyprlock || hyprlock --grace 2
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Atenúa a los 2.5 min
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Bloquea a los 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Apaga pantalla a los 10 min
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspende a los 30 min
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
